# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

excluded:
  - Carthage

line_length:
  ignores_comments: true
  ignores_function_declarations: true

trailing_comma:
    mandatory_comma: true
